<header>
    <?php include 'includes/logo.inc'; ?>
    <div class="search-bar">
        <input type="text" placeholder="Procure seu produto aqui" />
    </div>
    <div class="user-actions">
        <a href="login.php" class="user-actions-links"><ins>Entre</ins></a></button> ou<br>
        <a href="register.php" class="user-actions-links"><ins>Cadastre-se</a></ins></button>
        <a href="index.html"><img src="images/icon-fav.png" alt="Lista de Favoritos" width="30" height="30" /></a>
    </div>
</header>